frontend/models/Faq.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "faq".
 *
 * @property int $id
 * @property string $question
 * @property string $answer
 * @property int $user_id
 * @property int $_deleted
 * @property int $_status
 * @property string $created_at
 * @property string $updated_at
 */
class Faq extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'faq';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['question', 'answer', 'user_id'], 'required'],
            [['answer'], 'string'],
            [['user_id', '_deleted', '_status'], 'integer'],
            [['created_at', 'updated_at'], 'safe'],
            [['question'], 'string', 'max' => 160],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'question' => 'Question',
            'answer' => 'Answer',
            'user_id' => 'User ID',
            '_deleted' => 'Deleted',
            '_status' => 'Status',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }
}

frontend/controllers/FaqController.php
<?php

namespace frontend\controllers;

use Yii;
use app\models\Faq;
use app\models\FaqSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * FaqController implements the CRUD actions for Faq model.
 */
class FaqController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Faq models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new FaqSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Faq model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Faq model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Faq();

        if ($model->load(Yii::$app->request->post())) {

            $model->user_id = ((isset( Yii::$app->user->identity->id ))? Yii::$app->user->identity->id : null );

            if ($model->validate()) {
                if ($model->save()) {
                    return $this->redirect(['view', 'id' => $model->id]);
                }
            }
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Faq model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Faq model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Faq model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Faq the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Faq::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

frontend/views/faq/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Faq */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="faq-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->errorSummary($model) ?>

    <?= $form->field($model, 'question')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'answer')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'user_id')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/faq/_form_.php
<?php

use yii\helpers\Html;
use kartik\editors\Summernote;
use kartik\editors\Codemirror;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Faq */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="faq-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->errorSummary($model) ?>

    <div class="row">
        <div class="col-md-12">
            <?= $form->field($model, 'question')->textInput(['maxlength' => true]) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <?= $form->field($model, 'answer')->textarea(['rows' => 6]) ?>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
            </div>
        </div>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/faq/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\FaqSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="faq-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'question') ?>

    <?= $form->field($model, 'answer') ?>

    <?= $form->field($model, 'user_id') ?>

    <?= $form->field($model, '_deleted') ?>

    <?php // echo $form->field($model, '_status') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/faq/_search_.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\FaqSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="faq-search">

    <?php $form = ActiveForm::begin([
        'action' => [ ((isset( $whois ) && ( $whois == 'applicant' ))? '' : 'index' ) ],
        'method' => 'get',
    ]); ?>




    <div class="row">

        <div class="col-md-8">

        </div>
        <div class="col-md-4">

            <div class="row">

                <div class="col-md-6">
                    <div class="form-group" class="mt-4">
                        <?= $form->field($model, 'question')->textInput(['placeholder' => "Search By Question"])->label(false) ?>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group" class="mt-4">
                        <?= $form->field($model, 'answer')->textInput(['placeholder' => "Search By Answer"])->label(false) ?>
                    </div>
                </div>

            </div>
            <div class="row">

                <div class="col-md-12">
                    <div class="form-group">
                        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
                        <?= (\Yii::$app->user->can('delete-faq'))? Html::a('Create FAQ', [ '/faq/create' ], [ 'class' => 'btn btn-success' ]) : '' ; ?>
                    </div>
                </div>

            </div>

        </div>

    </div>



    <?php ActiveForm::end(); ?>

</div>

frontend/views/faq/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Faq */

$this->title = 'Create FAQ';
$this->params['breadcrumbs'][] = ['label' => 'Frequent Asked Question', 'url' => ['index']];
$this->params['breadcrumbs'][] = 'FAQ Creation Form';
?>
<div class="faq-create mr-2 ml-2 mt-4">

    <?= $this->render('_form_', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/faq/faqlist.php
<?php

use yii\helpers\Html;

use common\models\Esrf;
use common\models\Common;

?>
<div class="card card-<?= ((isset( $model->id ))? (( ( (int) $model->id % 3 ) == 0 )? 'warning' : (( ( (int) $model->id % 2 ) == 0 )? 'success' : 'primary' ) ) : 'info' ); ?> card-outline">
    <a class="d-block w-100" data-toggle="collapse" href="#collapse<?= ((isset( $model->id ))? $model->id : null ) ?>s">
        <div class="card-header">
            <h4 class="card-title w-100">
                <?= ((isset( $model->question ))? $model->question : "Unknown Basic FAQ's" ) ?>
            </h4>
        </div>
    </a>
    <div id="collapse<?= ((isset( $model->id ))? $model->id : null ) ?>s" class="collapse" data-parent="#accordion">
        <div class="card-body">
            <p class="" style=""><?= ((isset( $model->answer ))? $model->answer : "Details About Basic FAQ's" ) ?></p>
            <?= (\Yii::$app->user->can('update-faq'))? Html::a('<i class="fas fa-pencil-alt"></i>', [ 'update', 'id' => $model->id ], [ 'class' => 'card-link' ]) : '' ; ?>
            <?= (\Yii::$app->user->can('delete-faq'))? Html::a('<i class="fas fa-trash-alt"></i>', [ 'delete', 'id' => $model->id ], [ 'class' => 'card-link' ]) : '' ; ?>
        </div>
    </div>
</div>

frontend/views/faq/index-copy.php
<?php

use yii\helpers\Html;
use yii\widgets\ListView;
use sjaakp\collapse\Collapse;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\FaqSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Frequent Asked Question';
$this->params['breadcrumbs'][] = 'List of frequent asked question';
?>

<div class="application-index mr-2 ml-2">

    <div class="row">
        <div class="col-md-12">

            <?php echo $this->render( '_search_', [ 'model' => $searchModel ]); ?>

        </div>
    </div>


    <div class="row">

        <?= ListView::widget([

            'options' => [
                'tag' => 'div',
                'class' => 'col-12',
                'id' => 'accordion',
            ],

            'dataProvider' => $dataProvider,
            'itemView' => function ( $model )
            {

                $itemContent = $this->render(
                    '//faq/faqlist',
                    [
                        'model' => $model
                    ]);

                return $itemContent;

            },

            'itemOptions' => [
                'tag' => false
            ],

            'summary' => '',

        ]);
        ?>

    </div>


    <div class="col-md-12 col-lg-6 col-xl-4">
        <div class="card mb-2 bg-gradient-dark">
            <img class="card-img-top" src="<?= \Yii::$app->request->baseUrl . '/public/images/sample.png' ?>" alt="Dist Photo 1">
            <div class="card-img-overlay d-flex flex-column justify-content-end">
                <h5 class="card-title text-primary text-white">Card Title</h5>
                <p class="card-text text-white pb-2 pt-1">Lorem ipsum dolor sit amet, consectetur adipisicing elit sed do eiusmod tempor.</p>
                <a href="#" class="text-white">Last update 2 mins ago</a>
            </div>
        </div>
    </div>


</div>

frontend/views/faq/index.php
<?php

use yii\helpers\Html;
use yii\widgets\ListView;
use sjaakp\collapse\Collapse;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\FaqSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Frequent Asked Question';
$this->params['breadcrumbs'][] = 'List of frequent asked question';
?>

<div class="application-index mr-2 ml-2">

    <div class="row">
        <div class="col-md-12">

            <?php echo $this->render( 
                '//faq/_search_', 
                [ 
                    'model' => $searchModel, 
                    'whois' => ((isset( $whois ) && ( $whois == 'applicant' ))? 'applicant' : null ) 
                ]); 
            ?>

        </div>
    </div>


    <div class="row">

        <?= ListView::widget([

            'options' => [
                'tag' => 'div',
                'class' => 'col-12',
                'id' => 'accordion',
            ],

            'dataProvider' => $dataProvider,
            'itemView' => function ( $model )
            {

                $itemContent = $this->render(
                    '//faq/faqlist',
                    [
                        'model' => $model
                    ]);

                return $itemContent;

            },

            'itemOptions' => [
                'tag' => false
            ],

            'summary' => '',

        ]);
        ?>

    </div>


</div>

frontend/views/faq/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Faq */

$this->title = 'Update FAQ';
$this->params['breadcrumbs'][] = [ 'label' => 'Frequent Asked Question', 'url' => [ 'index' ] ];
$this->params['breadcrumbs'][] = $model->question;
?>
<div class="faq-update mr-2 ml-2 mt-4">

    <?= $this->render('_form_', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/faq/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Faq */

$this->title = 'FAQ Detail';
$this->params['breadcrumbs'][] = [ 'label' => 'Frequent Asked Question', 'url' => [ 'index' ] ];
$this->params['breadcrumbs'][] = $model->question;

\yii\web\YiiAsset::register($this);
?>
<div class="faq-view mr-2 ml-2 mt-5">

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <div class="row">
        <div class="col-md-6">

            <div class="card card-primary card-outline">
                <div class="card-header">
                    <h5 class="m-0">FAQ Detail</h5>
                </div>
                <div class="card-body">
                    <h6 class="card-title">
                        <?= ((isset( $model->question ))? $model->question : null ) ?>
                    </h6>

                    <p class="card-text">
                        <?= ((isset( $model->answer ))? $model->answer : null ) ?>
                    </p>
                    <?= Html::a('Return to FAQ', ['/faq/index', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
                </div>
            </div>

        </div>
    </div>

</div>